app/accounts/urls.py
from accounts.views import ActivateUserView, MyProfileView, SignUpView

from django.urls import path

app_name = 'accounts'


urlpatterns = [
    path('my-profile/<int:pk>/', MyProfileView.as_view(), name='my-profile'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('activate/<uuid:username>/', ActivateUserView.as_view(), name='activate-user'),
]

app/currency/urls.py
from currency.views import (
    ContactUsCreateView,
    GeneratePasswordBView, GeneratePasswordView,
    RateCreateView, RateDeleteView, RateDetailView, RateListView, RateUpdateView,
    SourceCreateView, SourceDeleteView, SourceDetailView, SourceListView, SourceUpdateView,
    contact_us_list,
    response_codes,
    )

from django.urls import path

app_name = 'currency'

# if you want to use view func instead of view class
# you shouldn`t use command .as_view() just write down the name of view func

urlpatterns = [

    # currency
    path('generate-password/', GeneratePasswordView.as_view()),
    path('generate-password-b/', GeneratePasswordBView.as_view()),

    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),

    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),

    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus-create'),

    path('contactUs/list/', contact_us_list),
    path('response-codes/', response_codes),
]

app/settings/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path as url
from django.views.generic import TemplateView

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title = "Open API",
        default_version='v1',
        description = "API for Currency",
        terms_of_service = '    https://www.google.com/politics/terms/',
        contact = openapi.Contact(email='contact@snippets.local'),
        license=openapi.License(name="BSD License"),
    ),
    public = True,
    permission_classes = (permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.v1.urls')),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('silk/', include('silk.urls', namespace='silk')),

    # API

    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

app/currency/models.py
from currency import choices as ch

from django.db import models

# Create your models here.


def upload_source_avatar(instance, filename):
    return f'source_avatars/{instance.id}/{filename}'


class Source(models.Model):
    source_url = models.CharField(max_length=256)
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=24, unique=True, editable=False)

    source_avatar = models.FileField(
        upload_to=upload_source_avatar,
        blank=True,
        null=True,
        default=None,
    )


class Rate(models.Model):
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)  # 123.45
    created = models.DateTimeField(auto_now_add=True)
    source = models.ForeignKey(Source, on_delete=models.CASCADE, related_name='rates')  # examples: privatbank, monobank
    type = models.CharField(max_length=3, choices=ch.RATE_TYPES)  # noqa examples: USD, EUR


class ContactUs(models.Model):
    email_to = models.EmailField(max_length=48)
    subject = models.CharField(max_length=32)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


class ResponseLog(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    status_code = models.PositiveSmallIntegerField()
    path = models.CharField(max_length=255)
    response_time = models.PositiveSmallIntegerField()
    request_method = models.CharField(max_length=8, choices=ch.REQUEST_METHOD_TYPES)

app/currency/forms.py
from currency.models import Rate, Source

from django import forms


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = {
            'buy',
            'sale',
            'source',
            'type'
        }


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = {
            'source_url',
            'name',
            'source_avatar',
        }

app/currency/views.py
from currency.forms import RateForm, SourceForm
from currency.models import ContactUs, Rate, Source
from currency.tasks import contact_us
from currency.utils import generate_password as gen_pass


# from django.conf import settings
# from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse as HR, JsonResponse as JR
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView, View


class IndexView(TemplateView):
    template_name = 'index.html'


# class View is used when you need to use your own code and mostly don`t want to have connection to parent class.
# Used when there are only classes in Views and you don`t want to change format and how code looks


class GeneratePasswordView(View):
    def get(self, request):
        password_len = int(request.GET.get('password-len'))
        password = gen_pass(password_len)
        return HR(password)


class GeneratePasswordBView(TemplateView):
    template_name = 'generate_password.html'

    def get_context_data(self, **kwargs: any):
        context = super().get_context_data(**kwargs)

        password_len = int(self.request.GET.get('password-len'))
        context['password'] = gen_pass(password_len)

        return context


# Rate CRUD + Details


class RateListView(ListView):
    queryset = Rate.objects.all().select_related('source').order_by('-created')
    template_name = 'rate_front/rate_list.html'


class RateCreateView(CreateView):
    model = Rate  # or queryset = Rate.object.all() if you want some accurate set
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')  # redirect place
    template_name = 'rate_front/rate_create.html'


class RateDetailView(LoginRequiredMixin, DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_front/rate_details.html'


class RateUpdateView(UserPassesTestMixin, UpdateView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')  # redirect place
    template_name = 'rate_front/rate_update.html'

    def test_func(self):
        return self.request.user.is_superuser


class RateDeleteView(UserPassesTestMixin, DeleteView):
    model = Rate
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_front/rate_delete.html'

    def test_func(self):
        return self.request.user.is_superuser


# Source CRUD + Details

class SourceCreateView(CreateView):
    model = Source  # or queryset = Rate.object.all() if you want some accurate set
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-list')  # redirect place
    template_name = 'sources_front/source_create.html'


class SourceListView(ListView):
    queryset = Source.objects.all()
    template_name = 'sources_front/source_list.html'


class SourceUpdateView(UpdateView):
    queryset = Source.objects.all()
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-list')  # redirect place
    template_name = 'sources_front/source_update.html'


class SourceDeleteView(DeleteView):
    model = Source
    success_url = reverse_lazy('currency:source-list')
    template_name = 'sources_front/source_delete.html'


class SourceDetailView(DetailView):
    queryset = Source.objects.all().prefetch_related('rates')
    template_name = 'sources_front/source_details.html'


class ContactUsCreateView(CreateView):
    model = ContactUs
    success_url = reverse_lazy('index')
    template_name = 'contactus_create.html'
    fields = (
        'email_to',
        'subject',
        'body'
    )

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        body = form.cleaned_data['body']
        email_to = form.cleaned_data['email_to']

        full_email_body = f'''
        Email from: {email_to}
        Body: {body}
        '''

        contact_us.apply_async(args=(subject, full_email_body))

        return super().form_valid(form)


def contact_us_list(request):
    contactus = ContactUs.objects.all()

    context = {
        'contactUs_list': contactus,
    }
    return render(request, 'contactUs_list.html', context=context)


def response_codes(request):
    response = HR('Responce', status=301, headers={'Location': '/rate/list/'})
    return response

app/currency/templates/rate_front/rate_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
Rate create
{%endblock%}

{% block main_content %}

Create Rate

<form method="post"> 
    {% csrf_token %}
    {{ form|crispy}}

    <button type="Submit"> Send to Django Serv </button>
</form>

{% endblock %}

app/currency/templates/rate_front/rate_delete.html
{% extends 'base.html' %}

{% block title %}
Rate Delete
{%endblock%}

{% block main_content %}

Rate Delete 

Are you sure you want to delete rate with id: {{ object.id }}?

<form method="post">
    {% csrf_token %}
    <button type="submit"> Delete </button>
</form>

{% endblock %}

app/currency/templates/rate_front/rate_details.html
{% extends 'base.html' %}

{% block title %}
Rate Details
{%endblock%}

{% block main_content %}

Rate Details

ID: {{ object.id }} <br>
Buy: {{ object.buy }} <br>
Sell: {{ object.sale }} <br>
Create: {{ object.created }} <br>
Source: {{ object.source.name }} <br>
Type: {{ object.type }} <br>

{% endblock %}

app/currency/templates/rate_front/rate_list.html
{% extends 'base.html' %}

{% block title %}
Rate list
{%endblock%}

{% block add_navbar %}
<li class="nav-item">
    <a class="nav-link" href = "{% url 'currency:rate-create' %}">Create Rate</a>
</li>
{% endblock %}

{% block main_content %}
<br>
<table class="table table-striped">
    <thead>
        <tr>    
            <th scope="col"> ID </th>
            <th scope="col"> Type </th>
            <th scope="col"> Sell </th> 
            <th scope="col"> Buy </th> 
            <th scope="col"> Source </th>
            {% if request.user.is_authenticated %}
                <th scope="col"> Details </th>
                {% if request.user.is_superuser %}
                    <th scope="col"> Admin actions </th> 
                {% endif %}
            {% endif %}
        </tr>
    </thead>
    {% for rate in rate_list %}
    <tbody>
        <tr>
            <th scope="row">{{rate.id}}</th>    
            <td>{{rate.get_type_display}}</td>
            <td>{{rate.sale}}</td>
            <td>{{rate.buy}}</td>
            <td>{{rate.source.name}}</td>
            {% if request.user.is_authenticated %}
                <td><a href="{% url 'currency:rate-details' pk=rate.pk %}"> Details </a></td>
                    {% if request.user.is_superuser %}
                    <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                         Admin actions
                        </button>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="{% url 'currency:rate-update' pk=rate.pk %}">Update</a>
                          <a class="dropdown-item" href="{% url 'currency:rate-delete' pk=rate.pk %}">Delete</a>
                        </div>
                      </div>
                      </td>
                    {% endif %}
            {% endif %}
        </tr>
    </tbody>
    {%endfor%}
</table>
{% endblock %}

app/currency/templates/rate_front/rate_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
Rate Details
{%endblock%}

{% block main_content %}

Rate Update of Rate {{ rate.id }}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit"> Send to Django Server </button>
</form>

{% endblock %}